<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<PackageOutputPath>$(LOCAL_NUGET)\</PackageOutputPath>
		<Copyright>Markus Raufer</Copyright>
		<Authors>Markus Raufer</Authors>
		<Description>A query library for Foundation.Graph.</Description>
		<PackageId>Foundation.Graph.Query</PackageId>
		<PackageTags>graph query; graph search</PackageTags>
		<ProductName>Foundation.Grap.Query</ProductName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Foundation" />
		<PackageReference Include="Foundation.Graph" />
	</ItemGroup>

</Project>
